
name: CI

on:
  push:
    branches: [ "nikel" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anyakichi/aosp-builder:14.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      DEV_NAME: nikel
      ARCH: arm64
      SUBARCH: arm64
      ARCH_ALIAS: aarch64
      CROSS_COMPILE: ${{ env.ARCH_ALIAS }}-linux-android-

    steps:

      - uses: actions/checkout@v3
        with: 
          repository: 'MT6797/kernel-3.18'

      - uses: actions/checkout@v3
        with:
          ref: test
          path: repo

      - name: Clone  tools
        uses: actions/checkout@v3
        with: 
          repository: 'LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9'
          path: ${{ env.CROSS_COMPILE }}

      - name: (Debug)Output build env
        run: |
          ls
          echo
          ls ${{ env.CROSS_COMPILE }}
          echo
          ls ${{ env.CROSS_COMPILE }}/bin
          echo
          ls /lib64/ld-linux-${{ env.ARCH }}.so.2
          ls /lib/${{ env.ARCH }}-linux-gnu/libm.so.6
          ls /lib/${{ env.ARCH }}-linux-gnu/libc.so.6
          echo
          ls /etc/ld.so.conf.d/*


      - name: Fix
        run: |
          ln -s $PWD/${{ env.CROSS_COMPILE }}/bin/* /usr/bin/
          #sed -i '381 a -fno-pie\\' Makefile
          

      - name: Build
        run: |

          mkdir out
          cp repo/config out/.config

          make O=out -j8 modules
      - name: Get release files name
        id: out-files
        shell: bash
        run: |
          mapfile  array_files < <(find out -name "*.ko")
          mkdir final_out
          for element in ${array_files[@]}
          do
          mv $element final_out/
          done

          #      - name:   debug 
          #        run: |
          

      - name: 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DEV_NAME }}-lastest
          files: |
            final_out/*





