name: CI

on:
  push:
      branches: [ "${{ github.ref_name }}" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anyakichi/aosp-builder:14.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      DEV_NAME: ${{ github.ref_name }}
      ARCH: arm64
      SUBARCH: arm64
      ARCH_ALIAS: aarch64

    steps:

      - name: Set environment variable
        run: |
          echo "CROSS_COMPILE=${{ env.ARCH_ALIAS }}-linux-android-" >> $GITHUB_ENV
          echo "$CROSS_COMPILE/bin" >> $GITHUB_PATH

      - name: Fetch kernel source
        uses: actions/checkout@v3
        with: 
          repository: 'MT6797/kernel-3.18'

      - name: Fetch config file
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: configs

      - name: Clone compile tools
        uses: actions/checkout@v3
        with: 
          repository: 'LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9'
          path: ${{ env.CROSS_COMPILE }}

      - name: Fix
        run: |

      - name: Build
        run: |
          mkdir out
          cp repo/kernelconfig out/.config

          make O=out -j8 modules

      - name: Get release files name
        shell: bash
        run: |
          mapfile  array_files < <(find out -name "*.ko")
          mkdir releases
          for element in ${array_files[@]}
          do
          mv $element final_out/
          done

      - name: Releases Files 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.DEV_NAME }}-lastest
          files: releases/*
